### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by ftp27** [bambocher/pocketsphinx-python#1]
Здравствуйте.

Пробовал установить ваш пакет через pip. Получил ошибку по типу:

**pip install PyPocketSphinx**

```
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kzwpsxsv/PyPocketSphinx/setup.py", line 73, in <module>
        long_description = read('readme.md'),
      File "/tmp/pip-build-kzwpsxsv/PyPocketSphinx/setup.py", line 66, in read
        return open(os.path.join(os.path.dirname(__file__), filename)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-kzwpsxsv/PyPocketSphinx/readme.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kzwpsxsv/PyPocketSphinx/setup.py", line 73, in <module>
        long_description = read('readme.md'),
      File "/tmp/pip-build-kzwpsxsv/PyPocketSphinx/setup.py", line 66, in read
        return open(os.path.join(os.path.dirname(__file__), filename)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-kzwpsxsv/PyPocketSphinx/readme.md'
```
Так же пробовал поставить через setup.py из клона вашего репозитория.

**python setup.py build**

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DHAVE_CONFIG_H -D_CRT_SECURE_NO_DEPRECATE -D_USRDLL -DSPHINXDLL -Isphinxbase/include -Isphinxbase/include/win32 -I/usr/include/python3.4m -c sphinxbase/src/libsphinxbase/util/profile.c -o build/temp.linux-x86_64-3.4/sphinxbase/src/libsphinxbase/util/profile.o
sphinxbase/src/libsphinxbase/util/profile.c: In function ‘ptmr_start’:
sphinxbase/src/libsphinxbase/util/profile.c:185:19: error: storage size of ‘start’ isn’t known
     struct rusage start;        /* CPU time */
                   ^
sphinxbase/src/libsphinxbase/util/profile.c:188:5: warning: implicit declaration of function ‘getrusage’ [-Wimplicit-function-declaration]
     getrusage(RUSAGE_SELF, &start);
     ^
sphinxbase/src/libsphinxbase/util/profile.c:188:15: error: ‘RUSAGE_SELF’ undeclared (first use in this function)
     getrusage(RUSAGE_SELF, &start);
               ^
sphinxbase/src/libsphinxbase/util/profile.c:188:15: note: each undeclared identifier is reported only once for each function it appears in
sphinxbase/src/libsphinxbase/util/profile.c:192:5: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
     gettimeofday(&e_start, 0);
     ^
sphinxbase/src/libsphinxbase/util/profile.c:185:19: warning: unused variable ‘start’ [-Wunused-variable]
     struct rusage start;        /* CPU time */
                   ^
sphinxbase/src/libsphinxbase/util/profile.c: In function ‘ptmr_stop’:
sphinxbase/src/libsphinxbase/util/profile.c:224:19: error: storage size of ‘stop’ isn’t known
     struct rusage stop;         /* CPU time */
                   ^
sphinxbase/src/libsphinxbase/util/profile.c:227:15: error: ‘RUSAGE_SELF’ undeclared (first use in this function)
     getrusage(RUSAGE_SELF, &stop);
               ^
sphinxbase/src/libsphinxbase/util/profile.c:224:19: warning: unused variable ‘stop’ [-Wunused-variable]
     struct rusage stop;         /* CPU time */
                   ^
sphinxbase/src/libsphinxbase/util/profile.c: In function ‘host_endian’:
sphinxbase/src/libsphinxbase/util/profile.c:322:9: warning: implicit declaration of function ‘unlink’ [-Wimplicit-function-declaration]
         unlink(file);
         ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

>$ python -V
Python 3.4.0
$ pip -V
pip 6.1.0.dev0 from /usr/local/lib/python3.4/dist-packages/pip-6.1.0.dev0-py3.4.egg (python 3.4)

**Comment by bambocher** [comment]
Приветствую.

К сожалению на текущий момент поддерживается только установка под Windows. Пакет создавался в первую очередь под эту платформу, т.к. именно в ней установка pocketsphinx наиболее затруднительна. Тем не менее я планировал добавить поддержку Linux в ближайшее время, а пока можно воспользоваться пакетами из репозитория python-sphinxbase и python-pocketsphinx.

**Comment by ftp27** [comment]
У меня Ubuntu и в отличии от арча в ней нет пакетов для 3-го питона, а мой проект как раз на нем и пишется.

**Comment by bambocher** [comment]
Исправил компиляцию под Linux 6ce683c937c401503227322d63f08b71deedeffd.
sphinxbase и pocketsphinx обновлены до 5prealpha.
Пока проверил только на Ubuntu 14.10, но должно работать и на других версиях и дистрибутивах.
Pypi репозиторий так же обновлен, попробуйте еще раз выполнить:
```bash
sudo pip install PyPocketSphinx
```
