### ISSUE TITLE
Error after successful installation

### ISSUE THREAD

**Issue by habibbaluwala** [bambocher/pocketsphinx-python#19]
I am using trying to install pocketsphinx-python on a 64 bit Windows server. I installed the module using pocketsphinx-0.1.3-cp27-cp27m-win_amd64.whl from pypi but after successful installation when I try to import pocketsphinx, I get the following error : 
------------------------------------------------------------------------------------------------------------------
import pocketsphinx
Traceback (most recent call last):

  File "<ipython-input-6-fd763eca10d8>", line 1, in <module>
    import pocketsphinx

  File "D:\Anaconda2\lib\site-packages\pocketsphinx\__init__.py", line 35, in <module>
    from sphinxbase import *

  File "D:\Anaconda2\lib\site-packages\sphinxbase\__init__.py", line 32, in <module>
    from .ad import *

  File "D:\Anaconda2\lib\site-packages\sphinxbase\ad.py", line 35, in <module>
    _ad = swig_import_helper()

  File "D:\Anaconda2\lib\site-packages\sphinxbase\ad.py", line 34, in swig_import_helper
    return importlib.import_module('_ad')

  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)

ImportError: No module named _ad

import ad
Traceback (most recent call last):

  File "<ipython-input-7-7b735f71af91>", line 1, in <module>
    import ad

ImportError: No module named ad

--------------------------------------------------------------------------------------------------------------

Do I need to install additional modules for the same. Apologies for any inconvenience.

**Comment by SoulReav** [comment]
Faced with this problem

**Comment by ankurgulati** [comment]
Any solution?

**Comment by feigaoxyz** [comment]
have you installed `swig`?

**Comment by vivek261991** [comment]
facing the same issue. can someone help me to resolve the issue.?

**Comment by DileepGog** [comment]
Still facing the issue any solution for this?

**Comment by cjcjcj7777** [comment]
facing the same issue. Someone please help me out to solve this issue

**Comment by Ahm3dRN** [comment]
i have the same problem could you solve it ?

**Comment by VijayalakshmiSundaravaradhan** [comment]
I am faing the same issue. I need pocketsphinx for arm.
