### ISSUE TITLE
audio_device selection in Livespeech

### ISSUE THREAD

**Issue by saibharani** [bambocher/pocketsphinx-python#23]

**Comment by slowrunner** [comment]
@saibharani 
You can try 
`speech = LiveSpeech(audio_device='2')` 

but if you are asking about an ALSA audio_device=2 you may get (like I am getting...):

`Error opening audio device 2 for capture: Connection refused
Traceback (most recent call last):
  File "keyword.py", line 16, in <module>
    speech = LiveSpeech(audio_device='2',verbose=True,sampling_rate=44100,lm=False,keyphrase='forward',kws_threshold='le-20')
  File "/usr/local/lib/python3.5/dist-packages/pocketsphinx/__init__.py", line 206, in __init__
    self.ad = Ad(self.audio_device, self.sampling_rate)
  File "/usr/local/lib/python3.5/dist-packages/sphinxbase/ad_pulse.py", line 124, in __init__
    this = _ad_pulse.new_Ad(audio_device, sampling_rate)
RuntimeError: new_Ad returned -1
`


LiveSpeech() seems to be trying pulseaudio, can it use ALSA device?  

Can we use a USB mic that only supports 44.1K and 48K sample_rate?

**Comment by bkravi-os-iot** [comment]
@slowrunner . may be this late as I joined this platform late.. May be you are not in this need anymore. But can be helpful for others.. By default LiveSpeech will call ad_pulse.py when sys.platform.startswith('linux').. as in your case it is calling ad_pulse. But if you want to change this call to as_alsa.py, simple change below lines in /usr/local/lib/python2.7/dist-packages/sphinxbase/__init__.py:

import sys

if sys.platform.startswith('win'):
    from .ad_win32 import *
elif sys.platform.startswith('darwin'):
    from .ad_openal import *
elif sys.platform.startswith('linux'):
    try:
        ### RAVI commented below and added line to import alsa. Otherwise, it will call pulse not alsa ###
        **_#from .ad_pulse import *_**
        **_from .ad_alsa import *_**
    except:
        from .ad_alsa import *

from .sphinxbase import *

Please check above in bold and italic.

Hope this helps

**Comment by Ozer0** [comment]
I got a sollution (works for me) (:
I have the same result as you when i use **arecord -l**, that means the hardware is **plughw:1,0**
Once you installed and builded pocketsphinx and sphinxbase, You can test it in a terminal with the following comand:
_`pocketsphinx_continuous -inmic yes -adcdev plughw:1,0`_
If it works, you can go to the next step with the LiveSpeech function with the parameter 
**audio_device='plughw:1,0'**

Example
```
import os
from pocketsphinx import LiveSpeech, get_model_path

model_path = get_model_path()

speech = LiveSpeech(
    audio_device='plughw:1,0',   #<---- Here is
    verbose=False,
    sampling_rate=16000,
    buffer_size=2048,
    no_search=False,
    full_utt=False,
    hmm=os.path.join(model_path, 'en-us'),
    lm=os.path.join(model_path, 'en-us.lm.bin'),
    dic=os.path.join(model_path, 'cmudict-en-us.dict')
)

for phrase in speech:
    print(phrase)
```
NOTE: I needed to change the __init__.py as @bkravi-os-iot said. (Thank you)

**Comment by judisonbacalso** [comment]
Hi @Ozer0 I was just wondering how did you change the init.py that @bkravi-os-iot said. because i cannot change it because it cannot be writable. Thanks!

**Comment by Ozer0** [comment]
Hi (:
Yes, what i did was chage the file __init__.py that is on the sphinxbase directory.

Just get into that directory and type:
                    sudo nano __init__.py
Change the two lines and it's done.
I'll put two screenshots to make it easier for you.


El 09/12/2019 6:54 p. m., Judison Bacalso <notifications@github.com> escribió:

Hi @Ozer0<https://github.com/Ozer0> I was just wondering how did you change the init.py that @bkravi-os-iot<https://github.com/bkravi-os-iot> said. because i cannot change it because it cannot be writable. Thanks!

**Comment by JDSNX** [comment]
Hi @Ozer0 
I have successfully change the init.py. But now I have another problem, take a look at this:

Error opening audio device plughw:1,0 for capture: Invalid argument
Traceback (most recent call last):
  File "/home/pi/Desktop/try.py", line 17, in <module>
    dic=os.path.join(model_path, 'cmudict-en-us.dict')
  File "/usr/local/lib/python3.7/dist-packages/pocketsphinx/__init__.py", line 206, in __init__
    self.ad = Ad(self.audio_device, self.sampling_rate)
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_pulse.py", line 122, in __init__
    this = _ad_pulse.new_Ad(audio_device, sampling_rate)
RuntimeError: new_Ad returned -1

I just follow what you said above about the audio_device.

**Comment by JDSNX** [comment]
By the way, I am running this in Raspberry Pi

**Comment by Ozer0** [comment]
Ok, my __init__.py looks like this. 
```
import sys

if sys.platform.startswith('win'):
    from .ad_win32 import *
elif sys.platform.startswith('darwin'):
    from .ad_openal import *
elif sys.platform.startswith('linux'):
    try:
        from .ad_alsa import *
    except:
        from .ad_alsa import *

from .sphinxbase import *
```

I had the same problem. Did you tried with this comand on the console?
`pocketsphinx_continuous -inmic yes -adcdev plughw:1,0`

If there's the problem like "ERROR continuos.c" maybe when you builded sphinxbase the Raspberry choosed pulseaudio instead of ALSA. So, check this link. http://robot.laylamah.com/?p=35

You have to verify Sphinxbase uses ALSA when you type the comand ./configure. 
This is because Sphinxbase always look first for pulseaudio, but in the documentation they said in embebed systems you should use ALSA.

**Even if you didn't installed pulseaudio this could happen (my case)**, so what I did was look for that pulseaudio.h file that makes that error. It was on a directory called Pulse in the /home/pi 
So I had to move it to another directory (Desktop) with the comand 
sudo mv pulse/ /home/pi/Desktop
Then I re-configured sphinxbase and realized sphinxbase choosed ALSA.

I think you could look for the file with whis comand on the console
`whereis pulseaudio`

**Comment by Ozer0** [comment]
Working with pocketsphinx python on Raspberry could be difficult because of many errors while installing all dependencies, that's why I'm working on a YouTube tutorial for begginers like me.
I'll share the video's link when finished (:

**Comment by JDSNX** [comment]
How can I choose the ALSA? 

I cannot find this when i configure the sphinxbase
![](http://robot.laylamah.com/wp-content/uploads/2013/10/configure_sphinxbase_correct.png)


I am really confused now :<

**Comment by Ozer0** [comment]
First of all do the steps to rename or move the "pulseaudio.h" file or if it's the case, uninstall pulseaudio. Then you have to re-configure sphinxbase with ./configure
When finish, look for the line that says 
**checking for alsa/aaoundlib.h .. yes**

**Comment by JDSNX** [comment]
I already re-configured my sphinxbase and I already saw checking for **alsa/aaoundlib.h .. yes**. And I also uninstall my pulseaudio. 

My problem now is when i check the alsamixer it has an error:
![image](https://user-images.githubusercontent.com/38557979/70595044-2d6d7980-1c1d-11ea-8e5b-59215529eb8b.png)

After I uninstall my pulseaudio this error came up. Been searching for a while for this error but cannot fixed.

**Comment by Ozer0** [comment]
Did you only uninstall pulseaudio?
What i did was look for the file i told you and moved it to another directory. 
I don't have installed pulseaudio on my raspberry and i don't have that problem while using alsautils.

**Comment by JDSNX** [comment]
I uninstall pocketsphinx and sphinxbase. Re-configured them all but when I check init.py i doesnt have any code.

Now, when i run this: **pocketsphinx_continuous -inmic yes -adcdev plughw:1,0** this is the output:
![image](https://user-images.githubusercontent.com/38557979/70606713-0b352500-1c38-11ea-8dad-88cc1fee94ec.png)

![image](https://user-images.githubusercontent.com/38557979/70606752-1daf5e80-1c38-11ea-93bd-4daf6dbaeeb2.png)


Can you determine what did I do wrong?

**Comment by Ozer0** [comment]
Are you sure you're trying to edit the sphinxbase's init.py?
Because pocketsphinx also has an init.py file, don't confuse them. 
You don't need to uninstall pocketsphinx or sphinxbase, you only have to re-configure them and install again. Try to do that

And about the problem, seems you need to specific the language model. You can try with a comand like this
![PicsArt_12-11-11 53 59](https://user-images.githubusercontent.com/51058686/70646651-f727fe00-1c0c-11ea-822e-da9a5946fe7d.jpg)

Try tp add the 3 parameter
-hmm is the en-us file
-lm = language model (.lm file)
-dict = dictionary (.dic file)
So go to your model folder and change the name to yours

**Comment by JDSNX** [comment]
Hi sir! I am able to run the continuous now. But the thing is i cannot run this line: **pocketsphinx_continuous -inmic yes -adcdev plughw:1,0** I can only run by using this **./src/programs/pocketsphinx_continuous -adcdev plughw:1,0 -nfft 2048 -samprate 48000**.

When im using the first one the error is this
![image](https://user-images.githubusercontent.com/38557979/70679359-d1aff880-1ccf-11ea-961f-468dc1d75344.png)

But when I use the second one i need to go to the pocketsphinx folder and run it there. I just followed the steps you linked to me before.

**Comment by JDSNX** [comment]
I fixed it using **sudo ldconfig**.

**Comment by Ozer0** [comment]
Happy to hear that. 
So now you can use a python script with pocketsphinx?

**Comment by JDSNX** [comment]
Yes, I am using the one you gave. Is there a way to catch the string? Or I will need the LiveSpeech?

**Comment by Ozer0** [comment]
Yeah, you have to use LiveSpeech and convert the "phrase" in code. 
See this video, it was helpful for me. 
https://www.youtube.com/watch?v=f_Pq7GDdxos

Also you can create your own dictionary and language model to reduce the error, it's very helpful. See this page (Step 8) https://medium.com/@ranjanprj/for-some-time-now-i-have-been-thinking-really-hard-to-build-a-diy-study-aid-for-children-which-uses-17ce90e72f43
Once you get the two files, you have to copy to the model folder and next use them on the python script (LiveSpeech parameters)

**Comment by JDSNX** [comment]
I followed the steps of the video you showed me and it has an error about the LiveSpeech
![image](https://user-images.githubusercontent.com/38557979/70703135-6df6f100-1d0a-11ea-8e97-4ab1b0946745.png)

But the using the pocketpshinx_continuous does not have an error. I even create my own dictionary and language.

**Comment by Ozer0** [comment]
Why are you executing your script with ./ ?
I don't know if that works but you have errors with python's keywords like "import", you should try with
`python speech.py`

**Comment by JDSNX** [comment]
Why I cannot import LiveSpeech?

**Comment by Ozer0** [comment]
That's was my problem too haha
Did you successfully installed pocketsphinx?

Here are the steps I followed, you should try with pip3 instead of pip. 
![20191212_215157](https://user-images.githubusercontent.com/51058686/70768862-c17a3680-1d2c-11ea-8595-4bd2446638c3.jpg)

**Comment by Ozer0** [comment]
First try to uninstall pocketsphinx python with
`pip uninstall pocketsphinx`

**Comment by JDSNX** [comment]
Hi! Do you have any idea how to deal with this?

![image](https://user-images.githubusercontent.com/38557979/70786258-31d59600-1dc7-11ea-86ff-e3767ca12c97.png)

**Comment by JDSNX** [comment]
Using python and python3 have different errors.
![image](https://user-images.githubusercontent.com/38557979/70786933-a9f08b80-1dc8-11ea-9fab-7c9547a4db69.png)

**Comment by Ozer0** [comment]
Hey man, did you solve it?

**Comment by JDSNX** [comment]
Nah. I keep getting the error like this. Same error for python 2 and 3.

![](https://user-images.githubusercontent.com/38557979/70789919-ef17bc00-1dce-11ea-9a41-2bb960dfcf06.png)

I changed the init.py but the error still there.

**Comment by JDSNX** [comment]
What parameters you put in the LiveSpeech?

**Comment by Ozer0** [comment]
See my first reply on this post

**Comment by JDSNX** [comment]
I got it now sir! Thank you so much! 👍  really appreciate your help!

**Comment by Ozer0** [comment]
Very happy to hear you finally can use it :D
You're welcome, I'm here to help people with the things i learned in so many forums like this. 

And not a Sir, I'm just 22 haha
Cheers from Mexico City 🇲🇽

**Comment by JDSNX** [comment]
Hi! Im back again! :D
I just wanna ask if it is possible in LiveSpeech to print the words when I stop speaking? Because when I have a certain sentence it will break. For example I will say "HI HOW ARE YOU" It will output like this
HI HOW
ARE YOU

Is there a way to catch it?

**Comment by Ozer0** [comment]
Do you want to do something with the words you say?
Like a command?

**Comment by JDSNX** [comment]
Yes. It cannot catch all of my sentence because when I try to use it, it will automatically read what I say. Is there way that the livespeech could run when im done talking?

**Comment by JDSNX** [comment]
I have a custom language model and dictionary already.

**Comment by Ozer0** [comment]
Ok, you have to use your .lm and .dict files in the  LiveSpeech's parameters function. Then you need to compare the string with the words you say
Here is a simple example

#Creating a command function
def command(word):
    if 'THE WORDS YOU WANT' in word:
        #do what you want, example
        print("Hello")
    else:
        print("Repeat it please")

for phrase in speech:
    word = str(phrase)
    #calling the commands function
    command(word)

**Comment by Ozer0** [comment]
![20191216_231542](https://user-images.githubusercontent.com/51058686/70967160-1d113080-205b-11ea-94bd-0ed759774721.jpg)

**Comment by Ozer0** [comment]
![20191216_231559](https://user-images.githubusercontent.com/51058686/70967207-429e3a00-205b-11ea-8184-a2c67200c845.jpg)

**Comment by Ozer0** [comment]
![20191216_232550](https://user-images.githubusercontent.com/51058686/70967276-78432300-205b-11ea-90ff-4c1ae1342819.jpg)

**Comment by JDSNX** [comment]
Ya, we have the same code. But I dont know why it will automatically print the phrase even if im not done talking yet.

**Comment by Ozer0** [comment]
The dictionary you created is conformed of only words?, or you wrote the wole phrases (two or more words)?
For example, I use a LIGHT ON command. So that's how i wrote the txt file to create the language model. 
```
LIGHT ON
LIGHT OFF
.
.
.
```
etc

**Comment by JDSNX** [comment]
What I wrote on my txt file is by word like OFF, ON, OPEN, CLOSE, etc. I cannot get the whole sentence because it will break automatically for example i will say "Please turn on the lights". The sentence will be separated to PLEASE TURN and ON THE LIGHTS. That is my problem as of now. I cannot get the whole phrase

**Comment by Ozer0** [comment]
Maybe you should try using the whole phrases in your txt file. 
Once you get that, you can use the whole phrase in your if sentence. 
I tell you this because the dictionary is different from the language model, the last one is used to determinate what words would be in front of some other word. 
You can read the CMUSphinx documentation to understand it.

**Comment by ismailryt** [comment]
Hi @Ozer0 ,I hope you want to help me
I already follow every step and all the step in conversation between you and @JDSNX 

But i still have a error like this

Error opening audio device plughw:1,0 for capture: Device or resource busy
Traceback (most recent call last):
  File "try.py", line 15, in <module>
    dic=os.path.join(model_path, '0175.dic')
  File "/usr/local/lib/python3.7/dist-packages/pocketsphinx/__init__.py", line 206, in __init__
    self.ad = Ad(self.audio_device, self.sampling_rate)
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_alsa.py", line 122, in __init__
    this = _ad_alsa.new_Ad(audio_device, sampling_rate)
RuntimeError: new_Ad returned -1

As you can see audio device plughw:1,0 is error, i already check using arecord -l, i hope you have any solution, anyway im using respeaker 4-mic array

**Comment by ismailryt** [comment]
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed4micvoicec [seeed-4mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 [bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by Ozer0** [comment]
> pi@raspberrypi:~ $ arecord -l
> **** List of CAPTURE Hardware Devices ****
> card 1: seeed4micvoicec [seeed-4mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 [bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0]
> Subdevices: 0/1
> Subdevice #0: subdevice #0
Hi there. 
Seems like you have the ALSA problem, have you changed the init file?

**Comment by ismailryt** [comment]
@Ozer0 Thanks for you reply, actually i already fix that but now i have this error 

RuntimeError: new_Decoder returned -1

I know this is happend because path problem, but i dont know how to set right path, i use your code 

model_path = get_model_path()

speech = LiveSpeech(
    audio_device='plughw:1,0',   #<---- Here is
    verbose=False,
    sampling_rate=16000,
    buffer_size=2048,
    no_search=False,
    full_utt=False,
    hmm=os.path.join(model_path, 'en-us-id'),
    lm=os.path.join(model_path, '0175.lm'),
    dic=os.path.join(model_path, '0175.dic')
)

Can you teach me this part of line " model_path = get_model_path() "
Thanks

**Comment by Ozer0** [comment]
> @Ozer0 Thanks for you reply, actually i already fix that but now i have this error
> 
> RuntimeError: new_Decoder returned -1
> 
> I know this is happend because path problem, but i dont know how to set right path, i use your code
> 
> model_path = get_model_path()
> 
> speech = LiveSpeech(
> audio_device='plughw:1,0', #<---- Here is
> verbose=False,
> sampling_rate=16000,
> buffer_size=2048,
> no_search=False,
> full_utt=False,
> hmm=os.path.join(model_path, 'en-us-id'),
> lm=os.path.join(model_path, '0175.lm'),
> dic=os.path.join(model_path, '0175.dic')
> )
> 
> Can you teach me this part of line " model_path = get_model_path() "
> Thanks

Hi, you solved the problem?

**Comment by ismailryt** [comment]
@Ozer0 actually no error right now, but now my problem is LiveSpeech cant recognize anything.. When i use [http://blog.justsophie.com/python-speech-to-text-with-pocketsphinx/](url) decode method, it can recognize 1 word then input over flowed because my raspberry pi cpu too slow

So my last hope is using LiveSpeech, im wondering why no error but cant recognize anything, when I use pocketsphinx_continuous, it works can record my word and can give me output. Can you help me

**Comment by Ozer0** [comment]
> @Ozer0 actually no error right now, but now my problem is LiveSpeech cant recognize anything.. When i use [http://blog.justsophie.com/python-speech-to-text-with-pocketsphinx/](url) decode method, it can recognize 1 word then input over flowed because my raspberry pi cpu too slow
> 
> So my last hope is using LiveSpeech, im wondering why no error but cant recognize anything, when I use pocketsphinx_continuous, it works can record my word and can give me output. Can you help me

Well, gotta say I used LiveSpeech in a Raspberry Zero so i don't think the CPU is your problem.
What it could be is you have to use an infinite loop (while: True), are you using that on your python code?
You can see part of my code above these answers

**Comment by ismailryt** [comment]
@Ozer0 i find the another solution! I use decode method not using LiveSpeech and can do hotword after that give intruction to system. Thanks for this thread and all of you guys, really helped me
