### ISSUE TITLE
RuntimeError: new_Ad returned -1

### ISSUE THREAD

**Issue by chintan121** [bambocher/pocketsphinx-python#25]
Error opening audio device (null) for capture: Connection refused
Traceback (most recent call last):
  File "1test.py", line 3, in <module>
    speech = LiveSpeech()
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/__init__.py", line 206, in __init__
    self.ad = Ad(self.audio_device, self.sampling_rate)
  File "/usr/local/lib/python2.7/dist-packages/sphinxbase/ad.py", line 102, in __init__
    this = _ad.new_Ad(audio_device, sampling_rate)
RuntimeError: new_Ad returned -1

my code is 
from pocketsphinx import LiveSpeech
for phrase in LiveSpeech(): print(phrase)

**Comment by YasserAntonio** [comment]
Same issue,i don't get why. Anyone solved this please ?

**Comment by MeckPommER** [comment]
Same issue here. Reason was pulseaudio not running. 
Checked with "ps -C pulseaudio"
Started with "pulseaudio -D" and LiveSpeech demo is now running without Problems.
