### ISSUE TITLE
Installation problem with conda and/or pip3

### ISSUE THREAD

**Issue by ptoche** [bambocher/pocketsphinx-python#57]
Managed to install `pocketsphinx-python` by downgrading from `Python 3.8` to `3.7`. Why won't this work with `3.8`? Oh well... Issue may be closed.  Thanks.

**Comment by ptoche** [comment]
Similar problem was reported here: https://stackoverflow.com/questions/61822972/how-to-use-pocketsphinx-with-anacondaprompt

**Comment by ptoche** [comment]
After removing conda,I was able to install `pocketsphinx`. However, I got this message:

         import pocketsphinx
        Traceback (most recent call last):

          File "<ipython-input-3-b2b224a4bfe4>", line 1, in <module>
            import pocketsphinx

          File "/usr/local/lib/python3.7/site-packages/pocketsphinx/pocketsphinx.py", line 29, in <module>
            import _pocketsphinx

        ModuleNotFoundError: No module named '_pocketsphinx'

Any ideas? Thanks.
